variables:
  CI_CD_UTILS_PATH: "/home/ci-cd-utils"

stages:
  - start
  - deploy
  - finish

notify_start:
  stage: start
  tags:
    - primal-shell-runner
  script:
    - $CI_CD_UTILS_PATH/notifications/deployment-start.sh

deploy:
  stage: deploy
  tags:
    - primal-shell-runner
  script:
    - docker build project -t korea-bus-api
    - kubectl apply -f deployment.yml
    - kubectl rollout restart deployment korea-bus-api

notify_success:
  stage: finish
  tags:
    - primal-shell-runner
  script:
    - $CI_CD_UTILS_PATH/notifications/deployment-success.sh

notify_error:
  stage: finish
  tags:
    - primal-shell-runner
  script:
    - $CI_CD_UTILS_PATH/notifications/deployment-fail.sh
  when: on_failure