variables:
  GIT_CLEAN_FLAGS: none

stages:
  - start
  - deploy
  - finish

notify_start:
  stage: start
  tags:
    - dev-shell-runner
  script:
    - telegram-send "Api service deployment started..."

deploy:
  stage: deploy
  tags:
    - dev-shell-runner
  script:
    - docker-compose up -d --build

notify_success:
  stage: finish
  tags:
    - dev-shell-runner
  script:
    - telegram-send "✅ Api service successfully deployed."

notify_error:
  stage: finish
  tags:
    - dev-shell-runner
  script:
    - telegram-send "❌ Api service fucked up."
  when: on_failure