apiVersion: apps/v1
kind: Deployment
metadata:
  name: korea-bus-api
  labels:
    app: korea-bus-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: korea-bus-api
  template:
    metadata:
      labels:
        app: korea-bus-api
    spec:
      containers:
      - name: korea-bus-api
        image: korea-bus-api
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
 
apiVersion: v1
kind: Service
metadata:
  name: korea-bus-api
  labels:
    app: korea-bus-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: korea-bus-api

---

apiVersion: v1
kind: Service
metadata:
  name: korea-bus-host
spec:
    type: ExternalName
    externalName: 192.168.99.1


---
apiVersion: v1
kind: Service
metadata:
   name: korea-bus-postgres
spec:
   clusterIP: None
   ports:
   - protocol: TCP
     port: 5432
     targetPort: 5432
   type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: korea-bus-postgres
subsets:
  - addresses:
    - ip: 192.168.99.1
    ports:
      - port: 5432
