apiVersion: apps/v1
kind: Deployment
metadata:
  name: korea-bus-api
  labels:
    app: korea-bus-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: korea-bus-api
  template:
    metadata:
      labels:
        app: korea-bus-api
    spec:
      containers:
      - name: korea-bus-api
        image: korea-bus-api
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app/storage 
          name: storage-volume
      volumes:
      - name: storage-volume
        path: /home/services_data/storage
        type: DirectoryOrCreate

---
 
apiVersion: v1
kind: Service
metadata:
  name: korea-bus-api
  labels:
    app: korea-bus-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: korea-bus-api



---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: korea-bus-api-postgres
  labels:
    app: korea-bus-api-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: korea-bus-api-postgres
  template:
    metadata:
      labels:
        app: korea-bus-api-postgres
    spec:
      containers:
      - name: korea-bus-api-postgres
        image: postgres:13.4-alpine3.14
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: storage-volume
      volumes:
      - name: storage-volume
        path: /home/services_data/dbdata
        type: DirectoryOrCreate

---
 
apiVersion: v1
kind: Service
metadata:
  name: korea-bus-api-postgres
  labels:
    app: korea-bus-api-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: korea-bus-api-postgres