version: '3.5'

services:
    api:
        container_name: kb-api
        restart: unless-stopped
        build:
            context: ./project
            dockerfile: Dockerfile
        depends_on: 
            - postgres
            - elasticsearch
        networks:
            - services-network
            - internal-network
        environment: 
            - JWT__SECRET=${JWT_SECRET}
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

    postgres:
        container_name: kb-postgres
        restart: unless-stopped
        build:
            context: ./postgres
            dockerfile: Dockerfile
        volumes:
            - ./data/dbdata:/var/lib/postgresql/data
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - 5432:5432
        networks:
            - internal-network

    elasticsearch:
        container_name: kb-elasticsearch
        restart: unless-stopped
        build:
            context: ./elasticsearch
            dockerfile: Dockerfile
        environment:
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./data/esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - internal-network

            
networks:
    internal-network:
        driver: bridge
    services-network:
        name: kb-services-network
