version: '3.5'

services:
    postgres:
        restart: unless-stopped
        image: postgres:13.4-alpine3.14
        volumes:
            - ${DATA_PATH}/dbdata:/var/lib/postgresql/data
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - 5432:5432

    elasticsearch:
        restart: unless-stopped
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        environment:
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ${DATA_PATH}/esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
