version: '3.5'

services:
    elasticsearch:
        restart: unless-stopped
        build:
            context: ./elasticsearch
            dockerfile: Dockerfile
        environment:
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ${DATA_PATH}/esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - internal-network
        deploy:
            resources:
                limits:
                    memory: 512M

            
networks:
    internal-network:
        driver: bridge
