version: '3.5'

services:
    postgres:
        restart: unless-stopped
        build:
            context: ./postgres
            dockerfile: Dockerfile
        volumes:
            - ${DATA_PATH}/dbdata:/var/lib/postgresql/data
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - 5432:5432
        networks:
            - internal-network

    elasticsearch:
        restart: unless-stopped
        build:
            context: ./elasticsearch
            dockerfile: Dockerfile
        environment:
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ${DATA_PATH}/esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - internal-network
        deploy:
            resources:
                limits:
                    memory: 512M

            
networks:
    internal-network:
        driver: bridge
